sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1257864014

  alioss:
    bucket-name: sky-take-out-cristwhy
    access-key-secret:
    access-key-id:
    endpoint: oss-cn-beijing.aliyuncs.com
